[package]
name = "rustwf"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = "3.2.5"
closure = "0.3.0"
csv = "1.1.6"
rand = {version = "0.8.5", features = ["small_rng"]}
threadpool = "1.8.1"

[lib]
name = "librustwf"
path = "src/lib.rs"

[[bin]]
name = "rustwf"
path = "src/rustwf.rs"
